data:
  constants:
    'LED_PIN': 4
    'RED_PIN': 17
    'GREEN_PIN': 22
    'BLUE_PIN': 24
  variables:
    'silent_mode': False
  default_commands:
    - 'lights_on'
    - 'lights_off'
    - 'fade_lights'
    - 'cancel'
  user_commands:
  server_response:
